name: Terraform Apply

on:
  workflow_run:
    workflows: ["Terraform Plan"]
    types:
      - completed

jobs:
  apply:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'



    steps:
      - name: Wait for Approval
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            const runId = context.runId;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const workflowId = context.workflow;

            await github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflowId,
              ref: context.ref,
              inputs: {
                approve: 'true'
              }
            });
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: .

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -input=false tfplan