name: Terraform Workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform environment variables
        run: |
          echo "Setting up Terraform environment variables..."
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Set Azure Subscription
        run: |
          echo "Setting Azure subscription..."
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --debug

      - name: Initialize Terraform
        run: |
          echo "Initializing Terraform..."
          terraform init

      - name: Import Existing Resource Group
        run: |
          echo "Importing existing resource group..."
          terraform import azurerm_resource_group.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rgakskubent

       - name: Import Existing Storage Account
        run: |
          echo "Importing existing storage account..."
          terraform import azurerm_storage_account.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rgakskubent/providers/Microsoft.Storage/storageAccounts/svtfstatestorage99

      - name: Import Existing Storage Container
        run: |
          echo "Importing existing storage container..."
          terraform import azurerm_storage_container.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rgakskubent/providers/Microsoft.Storage/storageAccounts/svtfstatestorage99/blobServices/default/containers/tfstatestoragecont

      - name: Assign Role to Service Principal
        run: |
          echo "Assigning role to service principal..."
          az role assignment create --assignee 84f6f1be-759f-4225-b540-e87ee015ea2c --role "Contributor" --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rgakskubent
    
      - name: Terraform Plan
        id: plan
        run: |
          echo "Running Terraform plan..."
          terraform plan -out=tfplan -detailed-exitcode || echo "Terraform plan failed."

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  apply:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform environment variables
        run: |
          echo "Setting up Terraform environment variables..."
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV

      - name: Set Azure Subscription
        run: |
          echo "Setting Azure subscription..."
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --debug

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: .
      - name: Initialize Terraform
        run: |
          echo "Initializing Terraform..."
          terraform init
      - name: Terraform Apply
        run: |
          echo "Applying Terraform plan..."
          terraform apply -input=false tfplan